export const COMPLETE_VEHICLE_BRANDS: Record<string, string[]> = {
  'Porsche': ['911', '918', 'Cayenne', 'Macan', 'Panamera', 'Boxster', 'Cayman', 'Taycan', '928', '944', '968'],
  'Maserati': ['Ghibli', 'Levante', 'Quattroporte', 'MC20', 'GranTurismo', 'Spyder', 'Coupe', 'GranCabrio'],
  'Lamborghini': ['Aventador', 'Huracán', 'Urus', 'Revuelto', 'Murciélago', 'Gallardo', 'Countach'],
  'Ferrari': ['SF90', 'F8', 'Roma', 'Portofino', 'Purosangue', 'F360', 'F430', 'F355', 'F308', '250', 'Mondial', '360', '430', '458', '488', '599', 'GTO', 'Testarossa', 'LaFerrari'],
  'Bugatti': ['Chiron', 'Veyron', 'Bolide', 'Divo'],
  'BMW': ['116', '118', '120', '220', '320', '330', '520', '530', '750', 'X1', 'X3', 'X5', 'X7', 'Z4', 'M340i', 'M440i', 'M550i', 'M5', 'M4', 'M3'],
  'Mercedes': ['A', 'B', 'C', 'E', 'S', 'G', 'GLA', 'GLB', 'GLC', 'GLE', 'GLS', 'CLA', 'C63 AMG', 'E63 AMG', 'G63 AMG', 'S63 AMG', 'AMG GT'],
  'Audi': ['A1', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'Q2', 'Q3', 'Q5', 'Q7', 'TT', 'R8'],
  'Volkswagen': ['Golf', 'Polo', 'Passat', 'Tiguan', 'Touareg', 'Beetle', 'Up', 'Transporter', 'Caddy'],
  'Peugeot': ['208', '308', '3008', '5008', '2008', '406', '607', 'Expert', 'Partner'],
  'Renault': ['Clio', 'Mégane', 'Espace', 'Scenic', 'Captur', 'Twingo', 'Master', 'Kangoo', 'Talisman'],
  'Citroën': ['C1', 'C3', 'C4', 'C5', 'Berlingo', 'Jumpy', 'C-Élysée'],
  'Fiat': ['500', 'Panda', 'Punto', 'Tipo', 'Ducato', 'Abarth'],
  'Alfa Romeo': ['Giulia', 'Stelvio', 'Tonale', '147', '156'],
  'SEAT': ['Ibiza', 'León', 'Ateca', 'Tarraco'],
  'Skoda': ['Octavia', 'Fabia', 'Superb', 'Kodiaq'],
  'Toyota': ['Yaris', 'Corolla', 'Camry', 'RAV4', 'Prius', 'Auris', 'Land Cruiser', 'Highlander'],
  'Honda': ['Jazz', 'Civic', 'Accord', 'CR-V', 'HR-V', 'Pilot'],
  'Nissan': ['Micra', 'Qashqai', 'X-Trail', 'Juke', 'Leaf', 'Almera'],
  'Mazda': ['2', '3', '6', 'CX-3', 'CX-5', 'CX-9', 'MX-5'],
  'Subaru': ['Impreza', 'Legacy', 'Outback', 'Forester', 'Crosstrek'],
  'Mitsubishi': ['Lancer', 'Outlander', 'Pajero', 'ASX'],
  'Suzuki': ['Swift', 'Vitara', 'Ignis', 'S-Cross', 'Jimny'],
  'Hyundai': ['i10', 'i20', 'i30', 'Tucson', 'Santa Fe', 'Kona'],
  'Kia': ['Picanto', 'Rio', 'Ceed', 'Sportage', 'Sorento', 'Niro'],
  'Ford': ['Fiesta', 'Focus', 'Mondeo', 'Kuga', 'S-Max', 'Galaxy'],
  'Chevrolet': ['Spark', 'Aveo', 'Cruze', 'Camaro', 'Corvette'],
  'Dodge': ['Challenger', 'Charger', 'Durango'],
  'Jeep': ['Wrangler', 'Grand Cherokee', 'Cherokee', 'Compass'],
  'Tesla': ['Model S', 'Model 3', 'Model X', 'Model Y'],
  'Volvo': ['V90', 'S90', 'XC90', 'XC60', 'S60', 'XC40'],
  'Land Rover': ['Defender', 'Discovery', 'Range Rover'],
  'Jaguar': ['XJ', 'XF', 'XE', 'F-PACE', 'F-TYPE'],
  'Aston Martin': ['DB11', 'DBS', 'DBX', 'Vantage'],
  'Bentley': ['Continental', 'Flying Spur', 'Bentayga'],
  'Rolls-Royce': ['Ghost', 'Wraith', 'Phantom', 'Cullinan'],
  'BYD': ['Yuan Plus', 'Qin', 'Song', 'Tang'],
  'Geely': ['Emgrand', 'Geometry', 'Monjaro'],
  'Great Wall': ['Haval', 'Wey', 'ORA'],
};

export const FUEL_TYPES = [
  { label: 'Essence', value: 'petrol' },
  { label: 'Diesel', value: 'diesel' },
  { label: 'Électrique', value: 'electric' },
  { label: 'Hybride', value: 'hybrid' },
  { label: 'Gaz', value: 'gas' },
  { label: 'Hybride rechargeable', value: 'phev' },
];

export const COMMON_ENGINES = {
  'petrol': ['1.0 L3', '1.2 L3', '1.2 TCe', '1.4 L4', '1.6 L4', '1.8 L4', '2.0 L4', '2.4 L4', '3.0 L6', '3.5 V6', '5.0 V8'],
  'diesel': ['1.4 dCi', '1.5 dCi', '1.6 TDCi', '1.9 TDI', '2.0 TDI', '2.2 TDCi', '3.0 TDI'],
  'electric': ['40 kWh', '60 kWh', '80 kWh', '100 kWh'],
  'hybrid': ['1.8L Hybrid', '2.0L Hybrid'],
};
